import socket
s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
s.bind((socket.gethostname(),6987))
s.listen()
print("waiting for 2 clients to connect")
addr=s.accept()
print(type(addr[0]))
"""print("waiting for 1 client to connect")
conn1,addr1=s.accept()
conn.send("welcome to server".encode())
conn1.send("welocome to server".encode())
while True:
          ms=input(str("<<"))
          ms=ms.encode()
          conn.send(ms)
          conn1.send(ms)
          msg=conn.recv(1024)
          msg=msg.decode()
          print("client <<",msg)
          conn1.send(msg.encode())
          msg1=conn1.recv(1024)
          msg1=msg1.decode()
          print("client1 <<",msg1)
          conn.send(msg1.encode())"""